### ISSUE TITLE
临时关闭插件 / pangu 在不合适的位置添加了空格

### ISSUE THREAD

**Issue by wfjsw** [MisaLiu/LiteLoaderQQNT-Pangu#1]
发现 pangu 会给 Windows 路径里边加空格：

原文：`你打开 %LOCALAPPDATA%\ZLUDA\ComputeCache`
转换后：`你打开 % LOCALAPPDATA%\ZLUDA\ComputeCache`

**Comment by MisaLiu** [comment]
在上游看到了类似的 issue：vinta/pangu.js#209

Pangu.js 本身很久没有更新了，之后会考虑换用更加完善的 fork 版

**Comment by MisaLiu** [comment]
[v1.0.2](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/releases/tag/1.0.2) 更换了 Pangu.js 并尝试修复了这个问题，烦请测试

**Comment by wfjsw** [comment]
![image](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/assets/2220320/4f26e5c6-58e0-4e23-80eb-e6f5d0035dee)
好似没有什么变化

**Comment by MisaLiu** [comment]
> ![image](https://private-user-images.githubusercontent.com/2220320/345692995-4f26e5c6-58e0-4e23-80eb-e6f5d0035dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjY1MTQsIm5iZiI6MTcyMDA2NjIxNCwicGF0aCI6Ii8yMjIwMzIwLzM0NTY5Mjk5NS00ZjI2ZTVjNi01OGUwLTRlMjMtODBlYi1lNmY1ZDAwMzVkZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDQxMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmRhOGMyMDAxOGU2ZGQ2OWNhODc5YjhjOTVhZGY4YjhmYTEwNjUwYjRkNjgzYjk1MDk4NTA3YWNhZjE0MjE2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2lndJpIOIaOC3i7QeqIxo3qp7CqabqLaQ5WBRw7auzQ) 好似没有什么变化

稍后我再尝试修复

如果可以的话，能否帮忙前往 [MisaLiu/pangu.js](https://github.com/MisaLiu/pangu.js) 修正这部分的逻辑？

**Comment by wfjsw** [comment]
https://github.com/MisaLiu/pangu.js/blob/c23edb770223f24a212cc9988ea6ae97da34a410/src/core.js#L69

看起来是这一条的问题。但是为什么有这样一条单独拎出来了？我不是特别理解

**Comment by wfjsw** [comment]
测试用例给了这样一个例子：
```
    it('處理英文與 % 符號', () => {
      assert.equal(pangu.spacing("丹寧控注意Levi's全館任2件25%OFF滿額再享85折！"), "丹寧控注意 Levi's 全館任 2 件 25% OFF 滿額再享 85 折！"); // eslint-disable-line quotes
    });
```

**Comment by wfjsw** [comment]
如果是测试给出的目的的话，暂时在前面添加了数字的限制

**Comment by MisaLiu** [comment]
[v1.0.3](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/releases/tag/1.0.3) 已同步 Pangu.js 修改并尝试修复问题，烦请再次测试

**Comment by wfjsw** [comment]
看起来是好了
