### ISSUE TITLE
给/后加空格后QQ机器人无法识别部分指令

### ISSUE THREAD

**Issue by Subao12138** [MisaLiu/LiteLoaderQQNT-Pangu#2]
QQ机器人大部分功能需要 /功能名 进行触发，给/后加空格后机器人无法识别。
当然给/后加空格肯定不是bug，想问下能否针对 / 这个情况做下处理

**Comment by MisaLiu** [comment]
跟 #1 应该是一个病原，我稍后自行处理一下吧

**Comment by MisaLiu** [comment]
[v1.0.2](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/releases/tag/1.0.2) 更换了 Pangu.js 并尝试修复了这个问题，烦请测试

**Comment by Subao12138** [comment]
似乎@机器人 后的指令依然存在问题，附测试截图
![image](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/assets/60761508/34927323-cdeb-415c-a18b-9fe3a564d72d)

![image](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/assets/60761508/332a2ec3-119c-4e76-940e-cca64b9fee56)

**Comment by MisaLiu** [comment]
> 不@机器人使用正常，但是似乎@机器人 后的指令依然存在问题，附测试截图 ![image](https://private-user-images.githubusercontent.com/60761508/345692481-34927323-cdeb-415c-a18b-9fe3a564d72d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjYyOTcsIm5iZiI6MTcyMDA2NTk5NywicGF0aCI6Ii82MDc2MTUwOC8zNDU2OTI0ODEtMzQ5MjczMjMtY2RlYi00MTVjLWExOGItOWZlM2E1NjRkNzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA0MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMzM2ZjIyYmU0YzJhMTUwNjQ5NmM0MDI4YjU5MDZjZTQzOTZmNTMxOGMzZDkzYTkzYTZjZDU0MWNlODBhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qKKxM44-VuMauJDi8gy_44PbgVN1TOvtE7l3ClYpuA)
> 
> ![image](https://private-user-images.githubusercontent.com/60761508/345692436-332a2ec3-119c-4e76-940e-cca64b9fee56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjYyOTcsIm5iZiI6MTcyMDA2NTk5NywicGF0aCI6Ii82MDc2MTUwOC8zNDU2OTI0MzYtMzMyYTJlYzMtMTE5Yy00ZTc2LTk0MGUtY2NhNjRiOWZlZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA0MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NWViMjBjZDU4NjczMDIwZGZkNDcwNmYzNjBmOGM4NWY5MjNlYTQ2ZThiYzY2YWIwMGQyODQxY2E3NzA3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._jQm9_zfiUzUTeYcYCJFSJILlwiCvpJnrxD3B3D7enc)

失算了  没考虑到官方 bot 和中文指令的使用场景

**Comment by MisaLiu** [comment]
[v1.0.3](https://github.com/MisaLiu/LiteLoaderQQNT-Pangu/releases/tag/1.0.3) 已同步 Pangu.js 修改并尝试修复问题，烦请再次测试

**Comment by Subao12138** [comment]
常用的功能都测试了  目前没有问题
